# Site settings
baseURL = "/"
# HTML Language Code Reference, such as en, zh-cn
languageCode = "en"
title = "AFP Colectiva"
theme = "hugo-theme-cactus-plus"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-66919923-1"
hasCJKLanguage = true

[params]
	name = "AFP Colectiva"
	description = "AFP Colectiva"
	bio = "Haz crecer tu pensión, con transparencia, participación e inversión ética de tus fondos."
	# Enter optionally your twitter account
	twitter = "basico-io"
	enableRSS = true

# Enable googleAnalytics
enableGoogleAnalytics = true